public class AccountOperations2 {
    public static Account setDefaultDescription(Account a) {
        a.Description = 'Default description';
        return a;
    }
    public static Account setDefaultDescription2(Account a) {
        a.Description = 'Default description 2';
        return a;
    }
    public static Account setDefaultDescription3(Account b) {
        b.Description = 'Default description 3';
        return b;
    }
}